//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mdsCLS.WSISBN {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webserviceX.NET", ConfigurationName="WSISBN.ISBNSoap")]
    public interface ISBNSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetISBNInformation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetISBNInformation(string Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/GetISBNInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetISBNInformationAsync(string Code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISBNSoapChannel : mdsCLS.WSISBN.ISBNSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SBNSoapClient : System.ServiceModel.ClientBase<mdsCLS.WSISBN.ISBNSoap>, mdsCLS.WSISBN.ISBNSoap {
        
        public SBNSoapClient() {
        }
        
        public SBNSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SBNSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SBNSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SBNSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetISBNInformation(string Code) {
            return base.Channel.GetISBNInformation(Code);
        }
        
        public System.Threading.Tasks.Task<string> GetISBNInformationAsync(string Code) {
            return base.Channel.GetISBNInformationAsync(Code);
        }
    }
}
